import { Pokemon } from "./pokemon";


export const POKEMONS: Pokemon[]=[
    {
        id: 1,
        hp: 25,
        cp: 5,
        name: "Bulbizarre",
        pictures: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
        types: ["Plante", "Poison"],
        created: new Date,
    },
    {
        id: 2,
        hp: 28,
        cp: 6,
        name: "Salamèche",
        pictures: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png",
        types: ["Feu"],
        created: new Date,
    },
    {
        id: 3,
        hp: 21,
        cp: 4,
        name: "Carapuce",
        pictures: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png",
        types: ["Eau"],
        created: new Date,
    },
    {
        id: 4,
        hp: 16,
        cp: 2,
        name: "Aspicot",
        pictures: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/013.png",
        types: ["Insecte", "Poison"],
        created: new Date,
    },
    {
        id: 5,
        hp: 30,
        cp: 7,
        name: "Roucool",
        pictures: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/016.png",
        types: ["Normal", "Vol"],
        created: new Date,
    },
    {
        id: 6,
        hp: 18,
        cp: 6,
        name: "Rattata",
        pictures: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/019.png",
        types: ["Normal"],
        created: new Date,
    },
    {
        id: 7,
        hp: 14,
        cp: 5,
        name: "Piafabec",
        pictures: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/021.png",
        types: ["Normal", "Vol"],
        created: new Date,
    },
    {
        id: 8,
        hp: 16,
        cp: 4,
        name: "Abo",
        pictures: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/023.png",
        types: ["Poison"],
        created: new Date,
    },
    {
        id: 9,
        hp: 21,
        cp: 7,
        name: "Pikachu",
        pictures: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/025.png",
        types: ["Electrik"],
        created: new Date,
    },
    {
        id: 10,
        hp: 19,
        cp: 3,
        name: "Sabelette",
        pictures: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/027.png",
        types: ["Normal"],
        created: new Date,
    },
    {
        id: 11,
        hp: 25,
        cp: 5,
        name: "Mélofée",
        pictures: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/035.png",
        types: ["Fée"],
        created: new Date,
    },
    {
        id: 12,
        hp: 17,
        cp: 8,
        name: "Groupix",
        pictures: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/037.png",
        types: ["Fée"],
        created: new Date,
    }
]